### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by abnerjacobsen** [adarqui/redis-exec#1]
@adarqui Hi I'm just trying to build my first go executable. How I can build redis-exec on my own Linux ? I'm running Alpine Linux 3.5 inside an Docker container. When I try to use your's release binary file I got this error message:

`sh: ./brooce: not found`

regards,

**Comment by adarqui** [comment]
Hey @abnerjacobsen!

Which release binary file? Do you mean, after you build it, the redis-exec executable?

As for building it, I have a simple Makefile, so running "make" will build the redis-exec executable. This just runs: go get gopkg.in/redis.v4 (grabs the goredis dependency) and go build.

A simple way to build go packages is:
```
go get -u ./... # grabs all dependencies
go build
```

As for "brooce", no idea what's going on with that. I tried searching google/overflow, nothing popping up. What's "brooce"?

What version of go are you using?

peace!

**Comment by abnerjacobsen** [comment]
@adarqui Sorry for my mistake, for some reason I confused redis-exec with https://github.com/SergeyTsalkov/brooce at the time of opening the ticket and mixed doubts that were of one with the other.

Anyway, with your help I was able to implement what I wanted using redis-exec. Thank you.

**Comment by adarqui** [comment]
Yeah I was confused haha. Thanks alot @abnerjacobsen. Also glad the code could be of some use to you! Thanks for the PR.

peace
